# Generated by Django 5.2.4 on 2025-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
