# Generated by Django 5.2.4 on 2025-07-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
