# Generated by Django 5.2.4 on 2025-08-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='price_item',
        ),
    ]
