# Generated by Django 5.2.4 on 2025-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0005_delete_price_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='price_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
    ]
