# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0006_alter_order_item_price_per_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='service',
        ),
        migrations.AddField(
            model_name='order_item',
            name='service_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
