# Generated by Django 5.2.4 on 2025-08-06 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0007_remove_order_item_service_order_item_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order_item',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='items_service_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saikialaundry.items')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saikialaundry.service')),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
