# Generated by Django 5.2.4 on 2025-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0009_order_delivery_charge_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
