# Generated by Django 5.2.4 on 2025-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0010_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='status',
        ),
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
