# Generated by Django 5.2.4 on 2025-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0011_remove_order_item_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
