# Generated by Django 5.2.4 on 2025-08-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0012_alter_order_item_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='saikialaundry.order'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
