# Generated by Django 5.2.4 on 2025-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0013_alter_order_item_order_alter_order_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Out for pickup', 'Out for pickup'), ('Picked Up', 'Picked Up'), ('In Progress', 'In Progress'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
    ]
