# Generated by Django 5.2.4 on 2025-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saikialaundry', '0014_order_transection_id_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('DeliveryPerson', 'DeliveryPerson'), ('Manager', 'Manager')], default='Customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
